apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-tz-env
  namespace: kube-example
spec:
  selector:
    matchLabels:
  env:
    - name: TZ
      value: Asia/Shanghai
      #时间校检，PodPreset类似于初始化，每个节点启动，都会初始他的设置到pod中