apiVersion: v1
kind: Pod
metadata:
  name: pvc-hostpath-pod
  labels:
    app: pvc-hostpath-pod
spec:
  volumes:
    - name: pv-hostpath
      persistentVolumeClaim:
        claimName: pvc-hostpath
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
    - name: pvc-hostpath-pod
      image: nginx:1.7.9
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pv-hostpath
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
