apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: kube-example
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      name: web
      targetPort: wdport
  type: NodePort